xxl:
  job:
    shouldInitialize: false

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        transaction:
          jta:
            platform: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-H2
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
    url: jdbc:h2:mem:xxl-job;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # 内存模式
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
    # 每次启动程序,都会执行该SQL脚本
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/h2/tables_xxl_job.sql
      encoding: utf-8
logging:
  level:
    com.zaxxer.hikari: WARN

